charts/deploymentlib/Chart.yaml
charts/deploymentlib/templates/_webapp.tpl

Found an issue with liveness an readiness probe.  In working with James, this is the fix.

fix for liveness and readiness probe headers. bump version

---

Justfile
README.md
charts/deploymentexample/values-local.yaml
charts/deploymentexample/values-production.yaml
charts/deploymentexample/values-staging.yaml
charts/deploymentexample/values.yaml
charts/ingressexample/values-production.yaml
charts/ingressexample/values.yaml
charts/ingresslib/Chart.yaml
charts/ingresslib/templates/_legacyingress.tpl

eliminate overlay of values files

---

charts/deploymentexample/output.staging.yaml
charts/deploymentexample/output.yaml
charts/deploymentexample/values.yaml
charts/deploymentlib/Chart.yaml
charts/deploymentlib/templates/_webapp.tpl
charts/ingressexample/output.staging.yaml
charts/ingressexample/values.yaml
charts/ingresslib/Chart.yaml
charts/ingresslib/templates/_legacyingress.tpl
charts/jobexample/output.staging.yaml
charts/jobexample/output.yaml
charts/jobexample/values.yaml
charts/joblib/Chart.yaml
charts/joblib/templates/_jobs.tpl
charts/joblib/templates/_worker.tpl
charts/podlib/Chart.yaml
charts/podlib/templates/_sealedsecret.tpl
charts/serviceaccountexample/output.staging.yaml
charts/serviceaccountexample/values.yaml
charts/serviceaccountlib/Chart.yaml
charts/serviceaccountlib/templates/_serviceaccount.tpl
charts/serviceexample/output.staging.yaml
charts/serviceexample/output.yaml
charts/serviceexample/values.yaml
charts/servicelib/Chart.yaml
charts/servicelib/templates/_externalip.tpl
charts/servicelib/templates/_externalname.tpl
charts/servicelib/templates/_webapp.tpl

this adds a set of universal labels to the manifests.

 add standard labels to all manifests

---

Dockerfile
examples/aruba-uxi-example/output-staging.yaml
examples/aruba-uxi-example/values-staging.yaml

aruba-uxi-example can be deployed via argocd now

feat: make aruba-uxi-example deployable via argo cd

---

.editorconfig
.github/pull_request_template.md
Justfile
README.md

common files from cookiecutter
JIRA Ticket: <https://uxi.atlassian.net/browse/BEP-148>

refactor: common files from cookiecutter repo

---

charts/aruba-uxi/CHANGELOG.md
charts/aruba-uxi/Chart.yaml
charts/aruba-uxi/README.md
charts/aruba-uxi/templates/cronjob.yaml
charts/aruba-uxi/templates/deployment.yaml
charts/aruba-uxi/values.example.yaml
examples/aruba-uxi-example/output-local.yaml
examples/aruba-uxi-example/output-staging.yaml
examples/aruba-uxi-example/values-staging.yaml

feat: add argument support for override docker image command

---

charts/aruba-uxi/CHANGELOG.md
charts/aruba-uxi/Chart.yaml
charts/aruba-uxi/values.example.yaml
examples/aruba-uxi-example/output-local.yaml
examples/aruba-uxi-example/output-staging.yaml
examples/aruba-uxi-example/values-staging.yaml

fix: worker commands

---

charts/aruba-uxi/CHANGELOG.md
charts/aruba-uxi/Chart.yaml
charts/aruba-uxi/templates/application-sentry-dsn.yaml
charts/aruba-uxi/templates/cronjob-sentry-dsn.yaml
examples/aruba-uxi-example/output-local.yaml
examples/aruba-uxi-example/output-staging.yaml
examples/aruba-uxi-example/values-staging.yaml

Sentry DSN sealed secrets were not being built correctly
JIRA Ticket: <https://uxi.atlassian.net/browse/UXI-1004>

fix: bug in created sentry dsn

---

CHANGELOG.md
charts/aruba-uxi/Chart.yaml
examples/aruba-uxi-example/output-local.yaml
examples/aruba-uxi-example/output-staging.yaml

docs: changelog typo

---

.github/workflows/change-log.yaml
CHANGELOG.md
charts/aruba-uxi/Chart.yaml
charts/aruba-uxi/templates/application-ingress.yaml
examples/aruba-uxi-example/output-local.yaml
examples/aruba-uxi-example/output-staging.yaml

apiVersion update (v1beta1) is deprecated 

feat: use newer apiVersion for ingress

---

CHANGELOG.md
charts/aruba-uxi/Chart.yaml
charts/aruba-uxi/templates/deployment.yaml
examples/aruba-uxi-example/output-local.yaml
examples/aruba-uxi-example/output-production.yaml
examples/aruba-uxi-example/output-staging.yaml

fix: replicaCount set to 0 was treated as false and default to 1

---

CHANGELOG.md
charts/aruba-uxi/Chart.yaml
charts/aruba-uxi/README.md
charts/aruba-uxi/templates/cronjob.yaml
charts/aruba-uxi/templates/deployment.yaml
examples/aruba-uxi-example/output-local.yaml
examples/aruba-uxi-example/output-production.yaml
examples/aruba-uxi-example/output-staging.yaml

Add env variable `APPLICATION_NAME` for each application where `APPLICATION_NAME={application-name}`
JIRA Ticket: https://uxi.atlassian.net/browse/UXI-1201

feat: Add env variable APPLICATION_NAME for each application.

---

examples/aruba-uxi-example/output-staging.yaml
examples/aruba-uxi-example/values-staging.yaml

fix: example service probe path

---

CHANGELOG.md
charts/aruba-uxi/Chart.yaml
charts/aruba-uxi/README.md
charts/aruba-uxi/templates/deployment.yaml
examples/aruba-uxi-example/output-local.yaml
examples/aruba-uxi-example/output-production.yaml
examples/aruba-uxi-example/output-staging.yaml

fix: some fixes

---

CHANGELOG.md
charts/aruba-uxi/Chart.yaml
charts/aruba-uxi/templates/_helpers.tpl
charts/aruba-uxi/templates/deployment.yaml
examples/aruba-uxi-example/output-local.yaml
examples/aruba-uxi-example/output-production.yaml
examples/aruba-uxi-example/output-staging.yaml

Adding the `APPLICATION_VERSION` as an environment variable which is built from the image tag. This is for auditing purposes

feat: adding APPLICATION_VERSION env variable

---

CHANGELOG.md
charts/aruba-uxi/Chart.yaml
charts/aruba-uxi/templates/application-ingress.yaml
examples/aruba-uxi-example/output-local.yaml
examples/aruba-uxi-example/output-production.yaml
examples/aruba-uxi-example/output-staging.yaml

the className was optional but should be required

fix: ingress className must be provided always

---

CHANGELOG.md
charts/aruba-uxi/Chart.yaml
charts/aruba-uxi/README.md
charts/aruba-uxi/templates/cronjob.yaml
charts/aruba-uxi/templates/deployment.yaml
charts/aruba-uxi/values.example.yaml
examples/aruba-uxi-example/Chart.yaml
examples/aruba-uxi-example/output-local.yaml
examples/aruba-uxi-example/output-production.yaml
examples/aruba-uxi-example/output-staging.yaml
examples/aruba-uxi-example/values-production.yaml

Some services have set their DD_SERVICE to something that is not the name of the service. This PR allows the service name to be controlled via the 

feat: ability to set DD_SERVICE

---

CHANGELOG.md

fix: change log fix

---

CHANGELOG.md
charts/aruba-uxi/Chart.yaml
charts/aruba-uxi/README.md
charts/aruba-uxi/templates/_helpers.tpl
charts/aruba-uxi/templates/cronjob.yaml
charts/aruba-uxi/templates/deployment.yaml
charts/aruba-uxi/values.example.yaml
examples/aruba-uxi-example/output-local.yaml
examples/aruba-uxi-example/output-production.yaml
examples/aruba-uxi-example/output-staging.yaml
examples/aruba-uxi-example/values-production.yaml

Update readme as questions were asked
https://uxi.atlassian.net/browse/BEP-737

feat: update readme info, add extraEnvironmentVariables to datadog and sentry

---

CHANGELOG.md
charts/aruba-uxi/Chart.yaml
charts/aruba-uxi/README.md
charts/aruba-uxi/templates/deployment.yaml
charts/aruba-uxi/values.example.yaml
examples/aruba-uxi-example/output-local.yaml
examples/aruba-uxi-example/output-production.yaml
examples/aruba-uxi-example/output-staging.yaml
examples/aruba-uxi-example/values-production.yaml
examples/aruba-uxi-example/values-staging.yaml

The readme and `values.example.yaml` files were drifting. This PR removes the content of the readme that can change often. Using the `values.example.yaml` file also helps to illustrate how the values file should look.
https://uxi.atlassian.net/browse/BEP-737

doc: make readme and values file simpler

---

CHANGELOG.md
charts/aruba-uxi/Chart.yaml
charts/aruba-uxi/templates/deployment.yaml
examples/aruba-uxi-example/output-local.yaml
examples/aruba-uxi-example/output-production.yaml
examples/aruba-uxi-example/output-staging.yaml
examples/aruba-uxi-example/values.yaml

Bugfix for incorrect indentation of pod resource values pulled from values.yml

Incorrect resource indentation

---

CHANGELOG.md
charts/aruba-uxi/Chart.yaml
charts/aruba-uxi/templates/cronjob.yaml
charts/aruba-uxi/values.example.yaml
examples/aruba-uxi-example/output-local.yaml
examples/aruba-uxi-example/output-production.yaml
examples/aruba-uxi-example/output-staging.yaml
examples/aruba-uxi-example/values-staging.yaml

feat: adding resources to cronjob

---

charts/aruba-uxi/README.md

doc: sentry-dsn info

---

CHANGELOG.md
charts/aruba-uxi/Chart.yaml
charts/aruba-uxi/templates/deployment.yaml
charts/aruba-uxi/values.example.yaml
examples/aruba-uxi-example/output-local.yaml
examples/aruba-uxi-example/output-production.yaml
examples/aruba-uxi-example/output-staging.yaml
examples/aruba-uxi-example/values-local.yaml
examples/aruba-uxi-example/values-production.yaml
examples/aruba-uxi-example/values-staging.yaml

Add the option to set a command for a liveness probe and fall back to the httpGet method if not set.

Configurable lliveness probe method

---

CHANGELOG.md
charts/aruba-uxi/Chart.yaml
charts/aruba-uxi/templates/deployment.yaml
examples/aruba-uxi-example/output-local.yaml
examples/aruba-uxi-example/output-production.yaml
examples/aruba-uxi-example/output-staging.yaml
examples/aruba-uxi-example/values-staging.yaml

Fix to render probe command arguments as a list instead of a list

[fix] Render probe command arguments as a list
